package Anexos;

public enum Genero {
    ACCION, ANIMACION, AVENTURA,
    BIOGRAFIA, COMEDIA, DOCUMENTAL,
    DRAMA, FANTASIA, INFANTIL,
    MUSICAL, ROMANCE, SCIFI,
    SUSPENSO, TERROR, WESTERN;
}
